name: Crypto Monitor

on:
  schedule:
    - cron: "*/5 * * * *" # кожні 5 хвилин
  workflow_dispatch:

jobs:
  check-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: node monitor.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          PRICE_CHANGE_THRESHOLD: "15"
